owner: InContextSolutions
repo: status.shoppermx.com

sites:
  - name: Public Website
    url: https://www.incontextsolutions.com
    type: globalping
  - name: ShopperMX
    url: https://www.shoppermx.com
    type: globalping
  - name: My ShopperMX
    url: https://my.shoppermx.com
    type: globalping
  - name: Help Site
    url: https://help.shoppermx.com
    type: globalping
  - name: EveryMan API
    url: https://everyman.shoppermx.com
    type: globalping

status-website:
  cname: status.shoppermx.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: InContext Status
  introTitle: "**InContext Status** monitors the health and uptime of our core platforms."
  introMessage: Welcome! This status page provides real-time monitoring and uptime information for InContext Solutions and ShopperMX services. All systems are tracked live, so you can trust this page for current service availability.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO